---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: django-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCR/TpCR5zXbGUl4Qt9tAy3OaHFJ6HFwzIt+eS7i3pKmSFBg8v/TFSZ3glzVxAi8OsatjfJF3Lr2ijYw/ksPz+82mRciW5PM79HRtA34MvFAOa/b+kw8YgyRBGSlkYWYL+4uWxfWCfaCeCvHeMTw2aFsAHWvqb73fY/g/LxCfe5A25p5uCpBaXWsE0a66IKndbrYHCdBwJckk2ZMykgHMaTKsVRcz9qGUyeoNLBzYwGtm/n4xrYw+GUPea9XW//QX9MyTkb9Uk7O6htoEuBnmifQe27FvN4v9J93QMpo3t/7XQaNQ5GZfDsQBszwULVxOa5eKsTjnl1zWHArRSqbTuMDrooLb1FhI6OPYECxbbgJiBpJriifoL96rDssLNZEYdk60ExRybnogL4FJvSmSmU5y30iFj8KRG99PvgSXDX/7rkR4j+OTCP2FH1mmsvjVMqE/TYpoYbE+MrbsSMWcYwSNAAB+2ZwHPc8AAtqxV7Jjo3ybC61ngFVgjrx2g6apwXxg889XCurezcpsSmj7YsVubwklu/n2o3PMvqNetHyEd3hvGMsFomdqXEQN1Z34YruSSzcW9zfKVy5mmAr7VulykXDnbSRnb1lXKJy+EsQuqGPU1WCm/IqvFE13GuHN9LKEZ5zOzIWJ/lupbFpS5J9ec6YLtVHOlxkybr9mUUSH7dzpKgVo2rQn6APrvA+lGj1BfvJYrox/+KPnEf
    DJANGO_SECRET_KEY: AgBtXvmfw6Kgk57dvhAOASVbsLRJEqtvjz+4EJSBwVglABhiEv0qH/OkRrTI8Tl2wCweWKu26FFTLJq5x0t3/jFvRbtVkNWGH36uSg3h5P1NlDgNoyIpu9BB60PW2Q4ZNQzOq6mcX/fDvBgDEF/S2f9OpwRjO8tqpgdcHxYcAB1iy8gNW5b4BBsusF3vT/gUMC6Tlp+izVrUYHcrZu8S8Fx0Bo2FPXvfCq/fIYNo/cTr+sNdVUzsqRrAirXYhmDvIi827wi0pmOYGIWrf1HY8pgmesUyJ0Fc/XO5RWU0FO5yqT+AnjaTxymmmLRyiI/AWplbws3Nq11Dmi27mGOecAoaQLb04/Iwc/5NEdS6Aq01wkqoU6KdeZdwhoop2FR3CarFwWjbHz2HtWWYX2oSFvpjIT1A5wo9UIsGFqCbjdS9Mqs1Yrn0hUaa3BjKEvOlRWHKeC7ZXZKS/mybpRs+4nbd9yZ6IvIc+ZGxoVz+4l4/NUa90NHCD4JOFl4NS2Sl3SRRuBzKJ1XWnDjsu1stTJLWnV8Z36SJEhfAZZ3/Ty0u07WYqBHB/0EXncDwJccXPBY7RzuOEivbQa86u59LSVPJm8Oe5HjOraE6Fc0HN0OLRwLeUaeCCvstezMGS1HqgL3xjnz1PWWMNVfjycme+YwM1XNAIg/Zyg6CxnDs8O8eUgLjslvXViQyFu+hGG5yqN3MgLPTa25x4wgPGy3a8qk/R24=
  template:
    metadata:
      creationTimestamp: null
      name: django-secret
      namespace: default
